### ISSUE TITLE
i can't locate grub directory in /etc/default/ directory.

### ISSUE THREAD

**Issue by sadegh-pz** [pspiagicw/dracula-grub#5]
In the second step of activating grub theme, the instruction asks to change theme in the /etc/default/grub directory, but there isn't such directory there. what is the problem? should i make one?

**Comment by pspiagicw** [comment]
/etc/default/grub is a file , it is the configuration file for GRUB for most distributions  . Don't create or try to write it yourself!
Your distribution might not have GRUB installed or use a different way to customize GRUB.

Can you give me your system information (Distribution) so I can research and add information about updating theme in your specific distribution?

**Comment by pspiagicw** [comment]
Closed due to inactivity
