### ISSUE TITLE
Grub theme not being around by grub

### ISSUE THREAD

**Issue by NovaViper** [pspiagicw/dracula-grub#6]
Hey, I installed the theme with the [AUR repo](https://aur.archlinux.org/packages/dracula-grub-theme-git) but grub doesn't seem to able to locate the theme at all, it doesn't say in the terimnal that it found the theme. Using ArchLinux with KDE Plasma and Grub 2

EDIT:
Found out that the theme needs to be installed in `/boot/grub/themes`, not `/usr/share/grub/dracula/theme`, Grub 2 doesn't seem to read in the /usr location at all. This is the same issue as #1 .

**Comment by pspiagicw** [comment]
Thanks for the heads up! Will test the same and update documentation

**Comment by pspiagicw** [comment]
Thanks! I tested  and confirmed the same! It is now updated in INSTALL.md

**Comment by NovaViper** [comment]
You're welcome!! ^^
