### ISSUE TITLE
Directory in Instructions doesn't work at least in my Arch Install

### ISSUE THREAD

**Issue by Akitarmo** [pspiagicw/dracula-grub#7]
I run Arch, I went with the instructions on the page https://draculatheme.com/grub. 
The Theme didn't work, it also was not detected with grub-customizer.

It was only when I used the Dir /boot/grub/themes that it automaticly appeared in the customizer and after that worked and looked great:)

**Comment by pspiagicw** [comment]
Thanks! I tested and confirmed the same , now INSTALL.md file is updated to include correct documentation.Sorry for the inconvenience cause.
